#application/deployment.yaml 

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: deploy-order-service
spec:
  selector:
    matchLabels:
      app: pod-order-service
      component: netcore-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: pod-order-service
        component: netcore-app
        version: 0.0.1
    spec:
      containers:
      - name: container-order-service
        image: thirul/order-service:0.0.1
        ports:
        - containerPort: 80
